version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./frontend/app
        target: /app
    ports:
      - "3000:3000"
    stdin_open: true  
